In [1]:
import sys
sys.path.append('pytorch_ssim')
from pytorch_ssim import SSIM

In [2]:
SSIM.__module__

'pytorch_ssim'

In [3]:
ssim_loss = SSIM(size_average=False).cuda()

jlkdjf
hello [0.0038659201394728076, 0.028565500784550377, 0.1353352832366127, 0.41111229050718745, 0.8007374029168081, 1.0, 0.8007374029168081, 0.41111229050718745, 0.1353352832366127, 0.028565500784550377, 0.0038659201394728076]


In [4]:
from pathlib import Path
img_paths = sorted(list(Path('~/data/FFHQ/images1024x1024/').expanduser().glob('*/*.png')))
len(img_paths)

70000

In [5]:
from random import sample
import skimage.io as io
import numpy as np
import torch

def load_img(p, cuda=True):
    img = io.imread(p).astype(np.float32) / 255.
    img = img.transpose(2,0,1)[None, ...]
    img = torch.from_numpy(img)
    if cuda:
        img = img.cuda()
    return img

for i in range(10):
    p1, p2, p3, p4 = sample(img_paths, 4)
    imgs1 = torch.cat([load_img(p1), load_img(p2)], dim=0)
    imgs2 = torch.cat([load_img(p3), load_img(p4)], dim=0)
    s1 = ssim_loss(imgs1,imgs2)
    print(s1)

hello [0.0038659201394728076, 0.028565500784550377, 0.1353352832366127, 0.41111229050718745, 0.8007374029168081, 1.0, 0.8007374029168081, 0.41111229050718745, 0.1353352832366127, 0.028565500784550377, 0.0038659201394728076]
tensor([0.2924, 0.3978], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.3848, 0.4970], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.4050, 0.4070], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.4400, 0.4118], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.3646, 0.2865], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.4356, 0.3374], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.3329, 0.4182], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.4107, 0.3605], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.4519, 0.3943], device='cuda:0')
same type: torch.cuda.FloatTensor
tensor([0.4062, 0.4212], device='cuda:0')


In [4]:
from random import sample
import skimage.io as io
import numpy as np
import torch

def load_img(p, cuda=True):
    img = io.imread(p).astype(np.float32) / 255.
    img = img.transpose(2,0,1)[None, ...]
    img = torch.from_numpy(img)
    if cuda:
        img = img.cuda()
    return img

# for i in range(10):
#     p1, p2 = sample(img_paths, 2)
#     img1, img2 = load_img(p1), load_img(p2)
#     s1 = ssim_loss(img1,img2)
#     print(s1.item())

In [5]:
ssim_pairwise_distance = np.empty((len(img_paths),len(img_paths)), np.float32)

## Too slow

In [6]:
from tqdm import tqdm
for i in tqdm(range(len(img_paths))):
    img1 = load_img(img_paths[i])
    for j in range(i, len(img_paths)):
        img2 = load_img(img_paths[j])
        ssim_pairwise_distance[i,j] = 1. - ssim_loss(img1, img2)

  0%|          | 1/70000 [1:38:04<114410:54:26, 5884.07s/it]

KeyboardInterrupt: 